name: Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: none
        DEFAULT_BRANCH: main
        WITH_V: true
        RELEASE_BRANCHES: main
        VERBOSE: true
        MAJOR_STRING_TOKEN: "#MAJOR"
        MINOR_STRING_TOKEN: "#MINOR"
        PATCH_STRING_TOKEN: "#PATCH"
        NONE_STRING_TOKEN: "#NONE"
        BRANCH_HISTORY: compare
