name: Bump version

on:
  pull_request:
    types:
      - closed
    branches:
      - testing

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: none
        DEFAULT_BRANCH: main
        WITH_V: true
        RELEASE_BRANCHES: testing
        VERBOSE: true
        MAJOR_STRING_TOKEN: "#MAJOR"
        MINOR_STRING_TOKEN: "#MINOR"
        PATCH_STRING_TOKEN: "#PATCH"
        NONE_STRING_TOKEN: "#NONE"
        BRANCH_HISTORY: last

    - name: Upload new backend version
      run: |
        latest_tag_version=$(git for-each-ref --sort=-v:refname --format '%(refname:lstrip=2)' | grep -E "^v?[0-9]+\.[0-9]+\.[0-9]+$" | head -n 1)
        echo "Latest backend version: ${latest_tag_version}"
        package_name="sonda-backend-testing-${latest_tag_version}"
        zip -r "${package_name}" . -x ".*"
        aws configure set region "eu-west-1"
        aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws s3api put-object --bucket sonda-backend-testing --key "${package_name}.zip" --body "${package_name}"
        echo "Package uploaded to s3: ${package_name}"
